### ISSUE TITLE
[bug] incorrectly fill up hour with current hour

### ISSUE THREAD

**Issue by liaoliaopro** [jinzhu/now#22]
reproduce test case as below:

  if New(n).MustParse("2002-10-12 00:14:56").Format(format) != "2002-10-12 00:14:56" {
             t.Errorf("Parse 2002-10-12 00:14:56")
  }

parse output is:  2002-10-12 {current hour}:14:56

**Comment by lss4** [comment]
This issue persists in the latest version as well, in now.Parse().

I can 100% reproduce it with the following code on a fresh project created in GoLand.

```
	testTime, err := now.Parse("2021-07-20T00:59:10Z")

	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(testTime)
```

The result is the same as the OP. Current hour is used instead (the code was executed at 8:00 local time for example).
```
2021-07-20 08:59:10 +0000 UTC
```

Additional reproducible test cases:
"2021-07-20T00:00:00Z" -> "2021-07-20 00:00:00 +0000 UTC" (PASS)
"2021-07-20T00:00:10Z" -> "2021-07-20 09:22:10 +0000 UTC" (FAIL, current hour and current minute used instead of 00)
"2021-07-20T00:01:00Z" -> "2021-07-20 09:01:00 +0000 UTC" (FAIL, current hour used instead of 00)
"2021-07-20T06:00:00Z" -> "2021-07-20 06:00:00 +0000 UTC" (PASS)

**Comment by lss4** [comment]
An update on the matter.

It seems the fix above only addressed the error for format "2006-01-02 15:04:05", but not "2006-01-02T15:04:05Z" (ISO 8601). The following test case would fail if I change "2002-10-12 00:14:56" to "2002-10-12T00:14:56Z". The result has the hour specified in `n` instead of 00.

```
now_test.go:32: Failed Parse 2002-10-12T00:14:56Z: actual: 2002-10-12 17:14:56, expected: 2002-10-12 00:14:56
```
